# Generated by Django 3.0.5 on 2020-04-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart', models.CharField(max_length=200)),
                ('arriver', models.TextField()),
                ('dateDepart', models.CharField(max_length=200)),
                ('dateArriver', models.CharField(max_length=200)),
                ('distance', models.CharField(max_length=200)),
                ('prix', models.CharField(max_length=200)),
            ],
        ),
    ]
