# Generated by Django 3.0.5 on 2020-04-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trajet',
            name='session',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trajet',
            name='arriver',
            field=models.CharField(max_length=200),
        ),
    ]
